export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}','./src/components/TopNavBar.jsx'],
   theme: {
        extend: {
                    "colors": {
                        "error": "#ffb4ab",
                        "on-tertiary-fixed": "#151f00",
                        "on-tertiary": "#273500",
                        "on-primary-fixed-variant": "#00522b",
                        "surface-container-highest": "#353534",
                        "on-secondary": "#002e69",
                        "on-secondary-container": "#dae4ff",
                        "surface-tint": "#43e188",
                        "inverse-surface": "#e5e2e1",
                        "tertiary-fixed-dim": "#a6d700",
                        "surface-variant": "#353534",
                        "surface": "#131313",
                        "secondary-fixed": "#d8e2ff",
                        "primary": "#60f99e",
                        "tertiary-container": "#a3d200",
                        "on-error": "#690005",
                        "surface-container": "#201f1f",
                        "on-error-container": "#ffdad6",
                        "inverse-primary": "#006d3b",
                        "surface-container-low": "#1c1b1b",
                        "on-tertiary-fixed-variant": "#3a4d00",
                        "secondary-fixed-dim": "#adc6ff",
                        "surface-container-lowest": "#0e0e0e",
                        "primary-container": "#3ddc84",
                        "secondary-container": "#0162cf",
                        "on-background": "#e5e2e1",
                        "on-surface": "#e5e2e1",
                        "on-surface-variant": "#bbcbbc",
                        "on-primary": "#00391c",
                        "outline": "#869587",
                        "secondary": "#adc6ff",
                        "on-secondary-fixed-variant": "#004494",
                        "on-primary-fixed": "#00210e",
                        "background": "#131313",
                        "surface-bright": "#393939",
                        "primary-fixed": "#66fea2",
                        "on-primary-container": "#005c31",
                        "on-tertiary-container": "#415700",
                        "error-container": "#93000a",
                        "outline-variant": "#3c4a3f",
                        "tertiary-fixed": "#bef500",
                        "surface-dim": "#131313",
                        "tertiary": "#baf000",
                        "primary-fixed-dim": "#43e188",
                        "surface-container-high": "#2a2a2a",
                        "inverse-on-surface": "#313030",
                        "on-secondary-fixed": "#001a41"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "lg": "24px",
                        "md": "16px",
                        "sm": "8px",
                        "xl": "32px",
                        "margin-desktop": "64px",
                        "margin-mobile": "16px",
                        "gutter": "24px",
                        "base": "8px",
                        "xs": "4px"
                    },
                    "fontFamily": {
                        "body-lg": ["Inter"],
                        "body-md": ["Inter"],
                        "headline-lg-mobile": ["Inter"],
                        "label-md": ["JetBrains Mono"],
                        "title-lg": ["Inter"],
                        "display-lg": ["Inter"],
                        "headline-lg": ["Inter"]
                    },
                    "fontSize": {
                        "body-lg": ["16px", { "lineHeight": "24px", "letterSpacing": "0.5px", "fontWeight": "400" }],
                        "body-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.25px", "fontWeight": "400" }],
                        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
                        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.5px", "fontWeight": "500" }],
                        "title-lg": ["22px", { "lineHeight": "28px", "fontWeight": "500" }],
                        "display-lg": ["57px", { "lineHeight": "64px", "letterSpacing": "-0.25px", "fontWeight": "700" }],
                        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }]
                    }
            }
    },
  plugins: [],       
};
